### ISSUE TITLE
Implement scrollspy for checklist view

### ISSUE THREAD

**Issue by ltwheeler** [dssit/chekhov#88]
To improve navigation with the new category based filtering, a scrollspy feature (see bootstrap) would be useful. 

An org could have potentially a very large number of categories, so there will need to be some limit to the number of categories listed, perhaps based on most commonly used with the remainder in a separate dropdown?

**Comment by cthielen** [comment]
It depends on the UI. In our original talks the category list would simply filter to that category alone (i.e. scrollspy wouldn't make sense because the categories are links to sets of data, not page markers within a larger data set). We did discuss having an "All" category to view all the lists at once but I'm not sure treating the category list as both as a scrollspy and links which effectively go to different pages (different data sets at least) will work together.

Let's keep the category links as links and not headings. The "All" category will suffer for it but then again, they can filter by category. #86 will help with this also.

**Comment by ltwheeler** [comment]
I like the simplicity of that structure.
It will feel a little silly if there are 7 checklists across 4 categories, and no way to see all 7 checklists at once.

However, if categories are used as we expect them to be, any given person should only be interested in one category (help desk, sysadmin, dev, etc.) and there would not be a use case to want to see multiple categories at once. So sounds good to me, links not headings.
